### ISSUE TITLE
localhost testing

### ISSUE THREAD

**Issue by leijing7** [zhaoyao91/meteor-accounts-wechat#1]
When I test my app on the localhost, I have to use below setting on both client and server side with ngrok. Otherwise the rediect uri would be http://localhost:3000/_oauth/wechat?close

Meteor.absoluteUrl.defaultOptions.rootUrl = 'http://*******.ngrok.io';

**Comment by zhaoyao91** [comment]
you can try to test on 127.0.0.1:3000 instead of localhost:3000

**Comment by leijing7** [comment]
The oauth's redirect_uri would be 127.0.0.1:3000 if I didn't set 

Meteor.absoluteUrl.defaultOptions.rootUrl = 'http://*******.ngrok.io'; //on client and server sides

Tencent would tell you something went wrong

**Comment by zhaoyao91** [comment]
That's the problem of policy of tencent. you should config the redirect-url in the platform of wechat
